### ISSUE TITLE
Parameter configuration

### ISSUE THREAD

**Issue by stutipathak5** [vvvwo/AIVS-project#3]
Great work! Could you please tell where in your code can I change the C configuration mentioned in your paper to have a curvature or sharp feature sensitive result? Thanks in advance!

**Comment by vvvwo** [comment]
Sorry, we don't provide curvature and sharp edge enhance code in this project. If you want implement the code, you can rewrite the simplification scheme based on the currect version. The sharp edge detection is implemented by CGAL VCM.

**Comment by stutipathak5** [comment]
Okay, thanks for letting me know.
