### ISSUE TITLE
The simplified point cloud is smaller than the source point cloud

### ISSUE THREAD

**Issue by hello-jo** [vvvwo/AIVS-project#4]
Excellent work, but I find that the simplified point cloud is less than the source point cloud in size, and the feeling is a certain size zoom, please tell me how to save the simplified point cloud according to the size of the source point cloud. Looking forward to your reply.

**Comment by vvvwo** [comment]
> Excellent work, but I find that the simplified point cloud is less than the source point cloud in size, and the feeling is a certain size zoom, please tell me how to save the simplified point cloud according to the size of the source point cloud. Looking forward to your reply.

Pls check the loadpointcloud.hpp, void PointCloud_Uniform(). This function is used to normalize the point cloud. If you want to keep the scale, then you can adjust the code.

**Comment by hello-jo** [comment]
thanks for your reply，and now it could work normally
